### PR TITLE
Delete redundant recommended settings

### PR DESCRIPTION
**Pull request by tatsuyafujisaki**
This pull request removes some settings from the recommended settings for simplicity, since they are the same as the defaults in Visual Studio Code.

- Dart Code Recommended Settings
    - https://dartcode.org/docs/recommended-settings
- Visual Studio Code Default Settings
    - https://code.visualstudio.com/docs/getstarted/settings#_default-settings

### CODE REVIEW

**Comment by tatsuyafujisaki** [comment]
@DanTup 
Could you review my pull request?

**Comment by DanTup** [comment]
Thanks! I was surprised we had things listed here that are default, but it looks like these changed after we first made this list:

https://github.com/microsoft/vscode-docs/commit/4a8f3f753c036b1d998326d09886ea3baf46bbd3
https://github.com/microsoft/vscode-docs/commit/623c9af6984b153071126be9f693db71acf181f7

These also exist in the extension itself here:

https://github.com/Dart-Code/Dart-Code/blob/d2ee2cc40369cafaf476039cf9697266ce415dc3/src/shared/constants.ts#L189

Let me know if you want to send a PR there, otherwise I'll update them. Thanks!

**Comment by tatsuyafujisaki** [comment]
Thanks! Let me leave the other update to you.

**Comment by DanTup** [comment]
I've updated this now (only one of the settings is actually included there, since we only write the Dart-specific section from the extension). Thanks!

**Pull request merged**
